[package]
name = "cl-server"
version = "0.1.0"
authors = ["Sven Thiele <sthiele78@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
clingo = { version = "0.7.0-dev", git = "https://github.com/potassco/clingo-rs", branch = "consume-ctl" }
rocket = "0.4.5"
thiserror = "1.0"
