name: CI Test

on: [push, pull_request]

jobs:
  build-linux:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      - name: Conda install clingo
        shell: bash -l {0}
        run: |
          conda install -c potassco/label/dev clingo
      - name: Conda install clingo-dl
        shell: bash -l {0}
        run: |
          conda install -c potassco/label/dev clingo-dl
      - name: Install Nightly
        run: rustup toolchain install nightly
      - name: Build
        run: |
          export CLINGO_LIBRARY_PATH=/usr/share/miniconda/envs/test/lib
          export CLINGO_DL_LIBRARY_PATH=/usr/share/miniconda/envs/test/lib
          cargo +nightly build --verbose
      - name: Run tests
        run: |
          export LD_LIBRARY_PATH=/usr/share/miniconda/envs/test/lib
          cargo +nightly test --verbose

  build-macos:
    runs-on: "macos-latest"
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      - name: Conda install clingo
        shell: bash -l {0}
        run: |
          conda install -c potassco/label/dev clingo
      - name: Conda install clingo-dl
        shell: bash -l {0}
        run: |
          conda install -c potassco/label/dev clingo-dl
      - name: Install Nightly
        run: rustup toolchain install nightly
      - name: Build
        run: |
          export CLINGO_LIBRARY_PATH=/usr/local/miniconda/envs/test/lib
          export CLINGO_DL_LIBRARY_PATH=/usr/local/miniconda/envs/test/lib
          cargo +nightly build --verbose
      - name: Run tests
        run: |
          export DYLD_LIBRARY_PATH=/usr/local/miniconda/envs/test/lib
          cargo +nightly test --verbose
