name: CI Test

on: [push, pull_request]

jobs:
  # build-linux:
  #   runs-on: "ubuntu-latest"
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: conda-incubator/setup-miniconda@v1
  #       with:
  #         auto-update-conda: true
  #         python-version: ${{ matrix.python-version }}
  #     - name: Conda install clingo
  #       shell: bash -l {0}
  #       run: |
  #         conda install -c potassco/label/dev clingo
  #         which clingo
  #     - name: Install Nightly
  #       run: rustup toolchain install nightly
  #     - name: Build
  #       run: cargo +nightly build --verbose
  #       env:
  #         CLINGO_LIBRARY_PATH: /usr/share/miniconda/envs/test/lib
  #     - name: Run tests
  #       run: cargo +nightly test --verbose
  #       env:
  #         LD_LIBRARY_PATH: /usr/share/miniconda/envs/test/lib

  build-macos:
    runs-on: "macos-latest"
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v1
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      - name: Conda install clingo
        shell: bash -l {0}
        run: |
          conda install -c potassco/label/dev clingo
          which clingo
          ls /usr/local/miniconda/envs/test/lib
      - name: Install Nightly
        run: rustup toolchain install nightly
      - name: Build
        run: cargo +nightly build --verbose
        env:
          CLINGO_LIBRARY_PATH: /usr/local/miniconda/envs/test/lib
      - name: Run tests
        run: |
          export DYLD_LIBRARY_PATH=/usr/local/miniconda/envs/test/lib
          export DYLD_FALLBACK_LIBRARY_PATH=$DYLD_LIBRARY_PATH
          export LD_LIBRARY_PATH=$DYLD_LIBRARY_PATH
          cargo +nightly test --verbose
